"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'fr';
  setLanguage: (lang: 'en' | 'fr') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.songs': 'Songs',
    'nav.chords': 'Chords',
    'nav.resources': 'Resources',
    'nav.about': 'About',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.contact': 'Contact',
    
    // Login & Register
    'auth.signIn': 'Sign In',
    'auth.signInTitle': 'Sign in to your account',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInDescription': 'Enter your email and password to access your account',
    'auth.signingIn': 'Signing in...',
    'auth.signUp': 'Sign Up',
    'auth.signUpTitle': 'Create Your Account',
    'auth.signUpDescription': 'Enter your information to create your account and start your musical journey',
    'auth.createAccount': 'Create Account',
    'auth.createAccountTitle': 'Create your account',
    'auth.startJourney': 'Start your musical journey today',
    'auth.createAccountDescription': 'Enter your information to create your account',
    'auth.creatingAccount': 'Creating Account...',
    'auth.getStarted': 'Get Started',
    'auth.dontHaveAccount': 'Don\'t have an account?',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.forgotPassword': 'Forgot password?',
    'auth.backToHome': 'Back to Home',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.createPassword': 'Create a password',
    'auth.confirmYourPassword': 'Confirm your password',
    'auth.fillAllFields': 'Please fill in all fields',
    'auth.invalidEmailPassword': 'Invalid email or password. Please check your credentials and try again.',
    'auth.loginFailed': 'Login failed. Please try again.',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters long',
    'auth.invalidEmail': 'Please enter a valid email address',
    'auth.registrationFailed': 'Registration failed. Please check your information and try again.',
    'auth.welcomeToPhinAccords': 'Welcome to PhinAccords',
    'auth.joinMusicians': 'Join thousands of musicians and worship leaders who use our platform to discover and learn gospel music chords.',
    'auth.accessChords': 'Access thousands of chord charts',
    'auth.interactiveDiagrams': 'Interactive piano and guitar diagrams',
    'auth.saveFavorites': 'Save your favorite songs and chords',
    'auth.builtBy': 'Built by',
    
    // 404 Not Found
    'notFound.title': '404 - Page Not Found',
    'notFound.description': 'The page you\'re looking for doesn\'t exist or has been moved.',
    'notFound.message': 'Don\'t worry, even the best musicians hit a wrong note sometimes. Let\'s get you back to the music!',
    'notFound.goHome': 'Go Home',
    'notFound.browseSongs': 'Browse Songs',
    'notFound.goBack': 'Go Back',
    'notFound.popularPages': 'Popular Pages',
    'notFound.songs': 'Songs',
    'notFound.pianoChords': 'Piano Chords',
    'notFound.guitarChords': 'Guitar Chords',
    'notFound.artists': 'Artists',
    'notFound.resources': 'Resources',
    
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.favorite': 'Favorite',
    'common.favorites': 'Favorites',
    'common.profile': 'Profile',
    'common.downloads': 'Downloads',
    'common.rating': 'Rating',
    'common.difficulty': 'Difficulty',
    'common.key': 'Key',
    'common.tempo': 'Tempo',
    'common.artist': 'Artist',
    'common.category': 'Category',
    'common.year': 'Year',
    'common.genre': 'Genre',
    'common.tags': 'Tags',
    'common.description': 'Description',
    'common.lyrics': 'Lyrics',
    'common.chords': 'Chords',
    'common.chordChart': 'Chord Chart',
    'common.chordProgression': 'Chord Progression',
    'common.transpose': 'Transpose',
    'common.originalKey': 'Original Key',
    'common.currentKey': 'Current Key',
    'common.capo': 'Capo',
    'common.strummingPattern': 'Strumming Pattern',
    'common.timeSignature': 'Time Signature',
    'common.website': 'Website',
    'common.ago': 'ago',
    'common.document': 'Document',
    'common.image': 'Image',
    'common.video': 'Video',
    'common.audio': 'Audio',
    'common.user': 'User',
    'common.bpm': 'BPM',
    'song.rateThisSong': 'Rate this song',
    'song.youRatedThis': 'You rated this',
    'song.clickToRemoveRating': 'Click to remove rating',
    'song.addComment': 'Add Comment',
    'song.hideComment': 'Hide Comment',
    'song.comment': 'Comment',
    'song.submitComment': 'Submit Comment',
    'song.recentRatings': 'Recent Ratings',
    'song.averageRating': 'Average Rating',
    'song.totalRatings': 'Total Ratings',
    'song.favoriteSongs': 'Favorite Songs',
    'song.songsYouveSaved': 'Songs you\'ve saved',
    'song.downloads': 'Downloads',
    'song.resourcesDownloaded': 'Resources downloaded',
    'song.ratingsGiven': 'Ratings Given',
    'song.songsYouveRated': 'Songs you\'ve rated',
    'song.memberSince': 'Member Since',
    'song.daysAgo': 'days ago',
    
    // Chords
    'chord.piano': 'Piano',
    'chord.allKeys': 'All Keys',
    'chord.allLevels': 'All Levels',
    'chord.easy': 'Easy',
    'chord.medium': 'Medium',
    'chord.hard': 'Hard',
    'chord.commonUses': 'Common Uses',
    'chord.alsoKnownAs': 'Also Known As',
    'chord.handPositionGuide': 'Hand Position Guide',
    'chord.techniqueTips': 'Technique Tips',
    'chord.practice': 'Practice',
    'chord.finger': 'Finger',
    'chord.pianoTechnique': 'Keep your fingers curved, press keys firmly but not tensely, and maintain a relaxed wrist position.',
    
    // French chord names
    'chord.C': 'Do',
    'chord.C#': 'Do#',
    'chord.Db': 'Ré♭',
    'chord.D': 'Ré',
    'chord.D#': 'Ré#',
    'chord.Eb': 'Mi♭',
    'chord.E': 'Mi',
    'chord.F': 'Fa',
    'chord.F#': 'Fa#',
    'chord.Gb': 'Sol♭',
    'chord.G': 'Sol',
    'chord.G#': 'Sol#',
    'chord.Ab': 'La♭',
    'chord.A': 'La',
    'chord.A#': 'La#',
    'chord.Bb': 'Si♭',
    'chord.B': 'Si',
    
    // Piano Chords Page
    'piano.title': 'Piano Chords',
    'piano.subtitle': 'Master every piano chord with interactive diagrams, note positions, and audio guides. Perfect for pianists of all levels.',
    'piano.chords': 'Piano Chords',
    'piano.interactive': 'Interactive',
    'piano.diagramsSounds': 'Diagrams & Sounds',
    'piano.learn': 'Learn',
    'piano.playPractice': 'Play & Practice',
    'piano.loading': 'Loading piano chords...',
    'piano.noChords': 'No piano chords found',
    'piano.tryAdjusting': 'Try adjusting your search or filters',
    'piano.clearFilters': 'Clear Filters',
    'piano.searchPlaceholder': 'Search chords...',
    'piano.filterByKey': 'Filter by Key',
    'piano.filterByDifficulty': 'Filter by Difficulty',
    'piano.advanced': 'Advanced',
    'piano.quickReference': 'Quick Reference',
    'piano.essentialProgressions': 'Essential chord progressions and common patterns',
    'piano.commonProgressions': 'Common Progressions',
    'piano.jazzProgressions': 'Jazz Progressions',
    'piano.pianoTechniques': 'Piano Techniques',
    'piano.inversions': 'Inversions',
    'piano.voicings': 'Voicings',
    'piano.progressions': 'Progressions',
    'piano.openClosed': 'Open & Closed',
    'piano.commonPatterns': 'Common Patterns',
    'piano.category': 'Category',
    'piano.sortBy': 'Sort By',
    'piano.allCategories': 'All Categories',
    'piano.major': 'Major',
    'piano.minor': 'Minor',
    'piano.seventh': '7th Chords',
    'piano.suspended': 'Suspended',
    'piano.name': 'Name',
    'piano.popularity': 'Popularity',
    
    // Keys
    'piano.key.C': 'C',
    'piano.key.C#': 'C#',
    'piano.key.Db': 'Db',
    'piano.key.D': 'D',
    'piano.key.D#': 'D#',
    'piano.key.Eb': 'Eb',
    'piano.key.E': 'E',
    'piano.key.F': 'F',
    'piano.key.F#': 'F#',
    'piano.key.Gb': 'Gb',
    'piano.key.G': 'G',
    'piano.key.G#': 'G#',
    'piano.key.Ab': 'Ab',
    'piano.key.A': 'A',
    'piano.key.A#': 'A#',
    'piano.key.Bb': 'Bb',
    'piano.key.B': 'B',
    
    
    // Hero Section
    'hero.badge': 'Gospel Music Resources',
    'hero.title': 'Find Gospel Music Chords & Resources',
    'hero.subtitle': 'Discover chord charts, lyrics, and resources for your worship ministry. Supporting gospel music enthusiasts with organized collections and easy-to-follow chord progressions.',
    'hero.searchPlaceholder': 'Search songs, artists, chords or lyrics...',
    'hero.browseSongs': 'Browse Songs',
    'hero.requestSong': 'Request a Song',
    
    // Footer
    'footer.description': 'Discover gospel music chords, lyrics, and resources for worship.',
    'footer.quickLinks': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.allResources': 'All Resources',
    'footer.learning': 'Learning',
    'footer.community': 'Community',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    
    // About Page
    'about.title': 'About PhinAccords',
    'about.subtitle': 'Making anyone an accomplished worship pianist, trained to excel in service and remain connected to the Holy Spirit.',
    'about.exploreSongs': 'Explore Songs',
    'about.joinCommunity': 'Join Community',
    'about.missionTitle': 'Our Mission',
    'about.missionText1': 'PhinAccords has a vision: to make anyone a worship pianist. Our mission is to equip and transform music enthusiasts into musicians capable of serving God with efficiency and excellence, guiding them in chord mastery and authentic spiritual worship.',
    'about.missionText2': 'This mission is motivated by two convictions:',
    'about.missionDistinctionTitle': 'Spiritual Distinction and Pure Worship',
    'about.missionDistinctionText': 'We have noticed that most learning platforms focus on secular songs. However, Scripture calls us to distinction:',
    'about.missionEfficiencyTitle': 'Easy Access and Service Efficiency',
    'about.missionEfficiencyText': 'We solve practical problems that hinder musicians: difficulty finding accurate Christian chord charts, scattered information (WhatsApp, etc.), and waiting for mentors.',
    'about.missionResources': 'Additionally, we will gradually provide essential resources beyond chords, covering: how to play, how to prepare to serve in worship, what it means to be a worship pianist, and much more.',
    'about.missionConclusion': 'PhinAccords solves all of this. Anyone can start their journey, instantly access complete chord charts, and learn to play the piano to become an effective instrument of worship in their church or community.',
    'about.versesDistinctionTitle': 'Distinction and Holiness',
    'about.versesServiceTitle': 'Excellence in Service',
    'about.verse1': '\"What partnership is there between righteousness and lawlessness? Or what fellowship does light have with darkness?\"',
    'about.verse1Ref': '(2 Corinthians 6:14, NASB)',
    'about.verse2': '\"Do not lack diligence; be fervent in spirit; serve the Lord.\"',
    'about.verse2Ref': '(Romans 12:11, CSB)',
    'about.verse3': '\"For we are the temple of the living God... Therefore, come out from among them and be separate, says the Lord.\"',
    'about.verse3Ref': '(2 Corinthians 6:16-17, CSB)',
    'about.verse4': '\"Do the work of an evangelist, fulfill your ministry.\"',
    'about.verse4Ref': '(2 Timothy 4:5, CSB)',
    'about.verse5': '\"Don\'t participate in the fruitless works of darkness, but instead expose them.\"',
    'about.verse5Ref': '(Ephesians 5:11, CSB)',
    'about.verse6': '\"Therefore, my dear brothers and sisters, be steadfast, immovable, always excelling in the work of the Lord, because you know that your labor in the Lord is not in vain.\"',
    'about.verse6Ref': '(1 Corinthians 15:58, CSB)',
    'about.versesConclusion': 'We clearly choose to walk in the light by providing exclusively resources based on gospel and Christian worship repertoire.',
    'about.getStarted': 'Get Started',
    'about.valuesTitle': 'Our Values',
    'about.valuesSubtitle': 'The principles that guide everything we do',
    'about.musicalExcellence': 'Ministry and Authentic Worship',
    'about.musicalExcellenceDesc': 'Our platform is a space to develop chord mastery while remaining connected to the Holy Spirit and serving the ministry with fervor.',
    'about.passionateMinistry': 'Targeted Gospel Resources (Light and Distinction)',
    'about.passionateMinistryDesc': 'We provide exclusively high-quality, accurate chord charts and worship resources for Christian repertoire, avoiding any confusion between light and darkness.',
    'about.communitySupport': 'Effective Service and Excellence',
    'about.communitySupportDesc': 'We enable musicians to serve God with efficiency and excellence, giving them the tools to excel in ministry and always be ready.',
    'about.qualityResources': 'Community Support',
    'about.qualityResourcesDesc': 'We aim to build and support worship communities to equip anyone and make them an accomplished worship pianist.',
    
    // Contact Page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have a question, suggestion, or need help? We\'d love to hear from you.',
    'contact.ourLocation': 'Our Location',
    'contact.location': 'Gatineau, Canada',
    'contact.sendMessage': 'Send us a Message',
    'contact.formDescription': 'Fill out the form below and we\'ll get back to you as soon as possible.',
    'contact.fullName': 'Full Name',
    'contact.emailAddress': 'Email Address',
    'contact.inquiryType': 'Type of Inquiry',
    'contact.selectInquiryType': 'Select inquiry type',
    'contact.generalInquiry': 'General Inquiry',
    'contact.songRequest': 'Song Request',
    'contact.technicalSupport': 'Technical Support',
    'contact.partnership': 'Partnership',
    'contact.feedback': 'Feedback',
    'contact.other': 'Other',
    'contact.subject': 'Subject',
    'contact.briefDescription': 'Brief description of your inquiry',
    'contact.message': 'Message',
    'contact.tellUsMore': 'Tell us more about your inquiry...',
    'contact.responseTime': 'Response Time',
    'contact.responseTimeText': 'We typically respond within 24 hours during business days.',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.clearForm': 'Clear Form',
    'contact.messageSent': 'Message Sent Successfully!',
    'contact.messageSentText': 'Thank you for reaching out. We\'ll get back to you within 24 hours.',
    'contact.sendAnother': 'Send Another Message',
    'contact.backToHome': 'Back to Home',
    
    // Resources Page
    'resources.title': 'Explore Our Resources',
    'resources.subtitle': 'Download guides, templates, and tutorials to enhance your musical journey.',
    'resources.categories': 'Categories',
    'resources.searchPlaceholder': 'Search resources...',
    'resources.loading': 'Loading resources...',
    'resources.noResources': 'No resources found matching your criteria.',
    'resources.loadMore': 'Load More Resources',
    'resources.remaining': 'remaining',
    'resources.featuredCollections': 'Featured Collections',
    'resources.beginnersBundle': 'Beginner\'s Bundle',
    'resources.beginnersBundleDesc': 'Start your journey with essential guides and practice routines.',
    'resources.viewCollection': 'View Collection',
    'resources.worshipLeaderPack': 'Worship Leader Pack',
    'resources.worshipLeaderPackDesc': 'Resources for effective worship leading and team management.',
    'resources.musiciansToolkit': 'Musician\'s Toolkit',
    'resources.musiciansToolkitDesc': 'Advanced theory, technical guides, and performance tips.',
    'resources.joinCommunity': 'Join Our Community',
    'resources.joinCommunityDesc': 'Connect with other musicians, share insights, and get support.',
    'resources.joinForum': 'Join the Forum',
    
    // Artists Page
    'artists.viewMode': 'View Mode',
    'artists.gridView': 'Grid View',
    'artists.listView': 'List View',
    
    // Songs
    'song.loading': 'Loading songs from database...',
    'song.noSongs': 'No songs found',
    'song.comeBack': 'Come back soon for new gospel songs!',
    'song.viewChords': 'View Chords',
    'song.viewAll': 'View All Songs',
    
    // Songs Page
    'songs.title': 'Gospel Songs',
    'songs.subtitle': 'Discover beautiful gospel songs with chord charts, lyrics and resources for worship',
    'songs.searchPlaceholder': 'Search songs, artists, chords or lyrics...',
    'songs.allSongs': 'All Gospel Songs',
    'songs.searchResults': 'Search Results',
    'songs.songsFound': 'songs found',
    'songs.loading': 'Loading songs...',
    'songs.fetching': 'Fetching the latest gospel songs from our collection',
    'songs.noSongs': 'No songs in the database',
    'songs.adminNeedsToAdd': 'The administrator must first add songs to the database.',
    'songs.noSongsFound': 'No songs found',
    'songs.tryAdjusting': 'Try adjusting your search terms or browse all songs.',
    'songs.clearFilters': 'Clear Filters',
    'songs.loadMore': 'Load More Songs',
    'songs.remaining': 'remaining',
    'songs.browseCollection': 'Browse our complete collection of gospel songs with chord charts and resources',
    'songs.songsAvailable': 'songs available',
    'songs.fromDatabase': 'From our database collection',
    'songs.allCategories': 'All Songs',
    'songs.classicHymn': 'Classic Hymn',
    'songs.contemporary': 'Contemporary',
    'songs.modernHymn': 'Modern Hymn',
    
    // Tips Section
    'tips.title': 'Tips & Resources',
    'tips.subtitle': 'Enhance your worship ministry with our organized tips and resources for gospel music',
    'tips.readingCharts': 'Reading Chord Charts',
    'tips.readingChartsDesc': 'Learn to read chord charts effectively. Start with basic major and minor chords, then progress to more complex progressions.',
    'tips.transposeSongs': 'Transposing Songs',
    'tips.transposeSongsDesc': 'Master the art of transposing songs into different keys. Essential skill for adapting songs to your vocal range or instrument.',
    'tips.leadingWorship': 'Leading Worship',
    'tips.leadingWorshipDesc': 'Tips for leading worship effectively. Learn about song flow, key changes, and engaging your congregation.',
    'tips.chordProgressions': 'Chord Progressions',
    'tips.chordProgressionsDesc': 'Understand common gospel chord progressions and how to create smooth transitions between songs in your set.',
    'tips.category.beginner': 'Beginner',
    'tips.category.intermediate': 'Intermediate',
    'tips.category.advanced': 'Advanced',
    'tips.moreResources': 'More resources coming soon from Heavenkeys Ltd.',
    
    // Admin
    // Admin Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.subtitle': 'Manage your chord collection and application settings.',
    'admin.dashboard.overview': 'Overview',
    'admin.dashboard.analytics': 'Analytics',
    'admin.dashboard.activity': 'Activity',
    'admin.dashboard.settings': 'Settings',
    'admin.dashboard.systemStatistics': 'System Statistics',
    'admin.dashboard.systemStatisticsDesc': 'Real-time updates of your platform performance',
    'admin.dashboard.refreshData': 'Refresh Data',
    'admin.dashboard.updating': 'Updating...',
    'admin.dashboard.songsInCollection': 'Songs in Collection',
    'admin.dashboard.totalSongsAvailable': 'Total songs available',
    'admin.dashboard.artists': 'Artists',
    'admin.dashboard.artistsInDatabase': 'Artists in database',
    'admin.dashboard.resources': 'Resources',
    'admin.dashboard.learningResources': 'Learning resources',
    'admin.dashboard.activeUsers': 'Active Users',
    'admin.dashboard.currentlyActive': 'Currently active',
    'admin.dashboard.recentActivity': 'Recent Activity',
    'admin.dashboard.latestSystemActivities': 'Latest system activities and changes',
    'admin.dashboard.noRecentActivity': 'No recent activity',
    'admin.dashboard.systemActivitiesWillAppear': 'System activities will appear here',
    'admin.dashboard.quickActions': 'Quick Actions',
    'admin.dashboard.commonAdminTasks': 'Common admin tasks and shortcuts',
    'admin.dashboard.manageSongs': 'Manage Songs',
    'admin.dashboard.manageArtists': 'Manage Artists',
    'admin.dashboard.manageUsers': 'Manage Users',
    'admin.dashboard.manageResources': 'Manage Resources',
    'admin.dashboard.viewAnalytics': 'View Analytics',
    'admin.dashboard.platformAnalytics': 'Platform Analytics',
    'admin.dashboard.comprehensiveInsights': 'Comprehensive insights into your platform\'s performance',
    'admin.dashboard.totalUsers': 'Total Users',
    'admin.dashboard.collections': 'Collections',
    'admin.dashboard.databaseStatus': 'Database Status',
    'admin.dashboard.connected': 'Connected',
    'admin.dashboard.lastSync': 'Last Sync',
    'admin.dashboard.justNow': 'Just now',
    'admin.dashboard.systemHealth': 'System Health',
    'admin.dashboard.healthy': 'Healthy',
    'admin.dashboard.growthRate': 'Growth Rate',
    'admin.dashboard.engagement': 'Engagement',
    'admin.dashboard.high': 'High',
    'admin.dashboard.performance': 'Performance',
    'admin.dashboard.excellent': 'Excellent',
    'admin.dashboard.systemActivity': 'System Activity',
    'admin.dashboard.trackSystemActivities': 'Track system activities and admin actions',
    'admin.dashboard.refresh': 'Refresh',
    'admin.dashboard.noActivityYet': 'No Activity Yet',
    'admin.dashboard.systemActivitiesWillAppearHere': 'System activities will appear here',
    'admin.dashboard.systemSettings': 'System Settings',
    'admin.dashboard.configureAdminPanel': 'Configure your admin panel and system preferences',
    'admin.dashboard.databaseConnection': 'Database Connection',
    'admin.dashboard.manageDatabaseSettings': 'Manage database settings',
    'admin.dashboard.systemNotifications': 'System Notifications',
    'admin.dashboard.receiveAdminAlerts': 'Receive admin alerts',
    'admin.dashboard.configure': 'Configure',
    'admin.dashboard.backupStatus': 'Backup Status',
    'admin.dashboard.lastBackup': 'Last backup: 2 hours ago',
    'admin.dashboard.backupNow': 'Backup Now',
    'admin.dashboard.adminActions': 'Admin Actions',
    'admin.dashboard.systemManagement': 'System management and maintenance',
    'admin.dashboard.securitySettings': 'Security Settings',
    'admin.dashboard.databaseManagement': 'Database Management',
    'admin.dashboard.performanceMonitoring': 'Performance Monitoring',
    'admin.dashboard.systemMaintenance': 'System Maintenance',
    'admin.activity': 'Activity',
    
    'admin.songs.title': 'Song Management',
    'admin.songs.subtitle': 'Manage your song collection, edit details, and organize content',
    'admin.songs.add': 'Add Song',
    'admin.songs.import': 'Import',
    'admin.songs.search': 'Search songs...',
    'admin.songs.allGenres': 'All Genres',
    'admin.songs.totalSongs': 'Total Songs',
    'admin.songs.genres': 'Genres',
    'admin.songs.filteredResults': 'Filtered Results',
    'admin.songs.noSongs': 'No songs found',
    'admin.songs.noSongsFilter': 'Try adjusting your search or filter criteria',
    'admin.songs.noSongsEmpty': 'Start by adding your first song to the collection',
    'admin.songs.addFirst': 'Add First Song',
    'admin.songs.created': 'Created',
    'admin.songs.updated': 'Updated',
    'admin.songs.deleteConfirm': 'Are you sure you want to delete this song?',
    'admin.songs.deleteSuccess': 'Song deleted successfully',
    'admin.songs.deleteError': 'Failed to delete song',
    'admin.songs.addTitle': 'Add New Song',
    'admin.songs.addDescription': 'Fill in the details to add a new song to your collection',
    'admin.songs.titleLabel': 'Title *',
    'admin.songs.titlePlaceholder': 'Enter song title',
    'admin.songs.artistLabel': 'Artist *',
    'admin.songs.selectArtist': 'Select an artist',
    'admin.songs.newArtist': 'Add New Artist',
    'admin.songs.newArtistName': 'New Artist Name',
    'admin.songs.newArtistPlaceholder': 'Enter artist name',
    'admin.songs.keyLabel': 'Key',
    'admin.songs.keyPlaceholder': 'e.g., C',
    'admin.songs.tempoLabel': 'Tempo (BPM)',
    'admin.songs.tempoPlaceholder': 'e.g., 120',
    'admin.songs.lyricsLabel': 'Lyrics',
    'admin.songs.lyricsPlaceholder': 'Enter song lyrics...',
    'admin.songs.cancel': 'Cancel',
    'admin.songs.addSuccess': 'Song added successfully',
    'admin.songs.addError': 'Failed to add song',
    'admin.songs.requiredFields': 'Please fill in title and artist',
    'admin.songs.artistCreated': 'New artist created successfully',
    'admin.songs.artistError': 'Failed to create artist',
    
    // Admin - Users Page (English)
    'admin.users.title': 'User Management',
    'admin.users.subtitle': 'Manage users, track analytics, and monitor user activity',
    'admin.users.refresh': 'Refresh',
    'admin.users.exportUsers': 'Export Users',
    'admin.users.userManagement': 'User Management',
    'admin.users.analytics': 'Analytics',
    'admin.users.totalUsers': 'Total Users',
    'admin.users.activeUsers': 'Active Users',
    'admin.users.newThisWeek': 'New This Week',
    'admin.users.onlineNow': 'Online Now',
    'admin.users.searchFilterManage': 'Search, filter, and manage your users',
    'admin.users.unknown': 'Unknown',
    'admin.users.desktop': 'Desktop',
    'admin.users.mobile': 'Mobile',
    'admin.users.tablet': 'Tablet',
    'admin.users.lastLogin': 'Last login',
    'admin.users.pageViews': 'Page views',
    'admin.users.downloads': 'Downloads',
    'admin.users.active': 'active',
    'admin.users.inactive': 'inactive',
    'admin.users.banned': 'banned',
    'admin.users.pending': 'pending',
    'admin.users.user': 'user',
    'admin.users.admin': 'admin',
    'admin.users.moderator': 'moderator',
    
    // Admin - Artists Page (additional English)
    'admin.artists.title': 'Artist Management',
    'admin.artists.subtitle': 'Manage artists, their profiles, and associated songs',
    'admin.artists.addArtist': 'Add Artist',
    'admin.artists.grid': 'Grid',
    'admin.artists.list': 'List',
    'admin.artists.totalArtists': 'Total Artists',
    'admin.artists.totalSongs': 'Total Songs',
    'admin.artists.avgSongsPerArtist': 'Avg Songs/Artist',
    'admin.artists.noArtists': 'No artists found',
    'admin.artists.addFirstArtist': 'Start by adding your first artist',
    'admin.artists.addFirst': 'Add First Artist',
    'admin.artists.editArtist': 'Edit Artist',
    'admin.artists.deleteArtist': 'Delete Artist',
    'admin.artists.deleteConfirm': 'Are you sure you want to delete this artist?',
    'admin.artists.deleteSuccess': 'Artist deleted successfully',
    'admin.artists.deleteError': 'Failed to delete artist',
    'admin.artists.addSuccess': 'Artist added successfully',
    'admin.artists.addError': 'Failed to add artist',
    'admin.artists.updateSuccess': 'Artist updated successfully',
    'admin.artists.updateError': 'Failed to update artist',
    'admin.artists.nameLabel': 'Artist Name',
    'admin.artists.namePlaceholder': 'Enter artist name',
    'admin.artists.bioLabel': 'Biography',
    'admin.artists.bioPlaceholder': 'Enter artist biography',
    'admin.artists.imageUrlLabel': 'Image URL',
    'admin.artists.imageUrlPlaceholder': 'Enter image URL',
    'admin.artists.websiteLabel': 'Website',
    'admin.artists.websitePlaceholder': 'Enter website URL',
    'admin.artists.save': 'Save',
    'admin.artists.cancel': 'Cancel',
    
    // Admin - Resources Page (English)
    'admin.resources.title': 'Resource Management',
    'admin.resources.subtitle': 'Manage learning resources, documents, and educational content',
    'admin.resources.import': 'Import',
    'admin.resources.addResource': 'Add Resource',
    'admin.resources.noResources': 'No resources found',
    'admin.resources.addFirstResource': 'Start by adding your first resource to the collection',
    'admin.resources.addFirst': 'Add First Resource',
    'admin.resources.totalResources': 'Total Resources',
    'admin.resources.totalDownloads': 'Total Downloads',
    'admin.resources.documents': 'Documents',
    'admin.resources.videos': 'Videos',
    
    // Admin - Analytics Page (English)
    'admin.analytics.title': 'Analytics Dashboard',
    'admin.analytics.subtitle': 'Comprehensive insights into your platform\'s performance and user engagement',
    'admin.analytics.exportReport': 'Export Report',
    'admin.analytics.totalSongs': 'Total Songs',
    'admin.analytics.totalUsers': 'Total Users',
    'admin.analytics.pageViews': 'Page Views',
    'admin.analytics.downloads': 'Downloads',
    'admin.analytics.userGrowth': 'User Growth',
    'admin.analytics.userAcquisitionGrowth': 'User acquisition and growth metrics',
    'admin.analytics.newUsersToday': 'New Users Today',
    'admin.analytics.newUsersThisWeek': 'New Users This Week',
    'admin.analytics.newUsersThisMonth': 'New Users This Month',
    'admin.analytics.growthRate': 'Growth Rate',
    'admin.analytics.userEngagement': 'User Engagement',
    'admin.analytics.howUsersInteract': 'How users interact with your platform',
    'admin.analytics.avgSessionsPerUser': 'Avg Sessions per User',
    'admin.analytics.avgSessionDuration': 'Avg Session Duration',
    'admin.analytics.bounceRate': 'Bounce Rate',
    'admin.analytics.activeUsers': 'Active Users',
    'admin.analytics.mostPopularSongs': 'Most Popular Songs',
    'admin.analytics.topPerformingSongs': 'Top performing songs by views',
    'admin.analytics.by': 'by',
    'admin.analytics.views': 'views',
    'admin.analytics.mostPopularArtists': 'Most Popular Artists',
    'admin.analytics.artistsWithMostSongs': 'Artists with the most songs',
    'admin.analytics.songs': 'songs',
    'admin.analytics.artist': 'Artist',
    
    // Admin - Settings Page (English)
    'admin.settings.title': 'Settings',
    'admin.settings.subtitle': 'Configure your application settings and preferences',
    'admin.settings.reset': 'Reset',
    'admin.settings.saveChanges': 'Save Changes',
    'admin.settings.generalSettings': 'General Settings',
    'admin.settings.basicConfiguration': 'Basic application configuration',
    'admin.settings.siteName': 'Site Name',
    'admin.settings.adminEmail': 'Admin Email',
    'admin.settings.siteDescription': 'Site Description',
    'admin.settings.siteUrl': 'Site URL',
    'admin.settings.databaseSettings': 'Database Settings',
    'admin.settings.connectionHealth': 'Database connection and health status',
    'admin.settings.databaseStatus': 'Database Status',
    'admin.settings.healthy': 'healthy',
    'admin.settings.connection': 'Connected to Supabase',
    'admin.settings.lastBackup': 'Last Backup',
    'admin.settings.testConnection': 'Test Database Connection',
    'admin.settings.securitySettings': 'Security Settings',
    'admin.settings.configureSecurity': 'Configure security and access controls',
    'admin.settings.twoFactorAuth': 'Two-Factor Authentication',
    'admin.settings.require2FA': 'Require 2FA for admin access',
    'admin.settings.ipWhitelist': 'IP Whitelist',
    'admin.settings.restrictAdminAccess': 'Restrict admin access to specific IPs',
    'admin.settings.sessionTimeout': 'Session Timeout (minutes)',
    'admin.settings.notificationSettings': 'Notification Settings',
    'admin.settings.configureNotifications': 'Configure system notifications and alerts',
    'admin.settings.emailNotifications': 'Email Notifications',
    'admin.settings.sendEmailAlerts': 'Send email alerts for system events',
    'admin.settings.systemAlerts': 'System Alerts',
    'admin.settings.showSystemAlerts': 'Show system alerts in admin panel',
    'admin.settings.maintenanceMode': 'Maintenance Mode',
    'admin.settings.putSiteInMaintenance': 'Put the site in maintenance mode',
    'admin.settings.performanceSettings': 'Performance Settings',
    'admin.settings.optimizePerformance': 'Optimize application performance and caching',
    'admin.settings.cachingEnabled': 'Caching Enabled',
    'admin.settings.enableApplicationCaching': 'Enable application caching',
    'admin.settings.cdnEnabled': 'CDN Enabled',
    'admin.settings.useCDN': 'Use CDN for static assets',
    'admin.settings.compressionEnabled': 'Compression Enabled',
    'admin.settings.enableGzipCompression': 'Enable gzip compression',
    'admin.settings.imageOptimization': 'Image Optimization',
    'admin.settings.optimizeImagesAutomatically': 'Optimize images automatically',
    
    // Admin - Common (English)
    'admin.common.adminPanel': 'Admin Panel',
    'admin.common.administration': 'ADMINISTRATION',
    'admin.common.dashboard': 'Dashboard',
    'admin.common.songs': 'Songs',
    'admin.common.artists': 'Artists',
    'admin.common.users': 'Users',
    'admin.common.resources': 'Resources',
    'admin.common.analytics': 'Analytics',
    'admin.common.settings': 'Settings',
    'admin.common.quickActions': 'QUICK ACTIONS',
    'admin.common.addSong': 'Add Song',
    'admin.common.viewAnalytics': 'View Analytics',
    'admin.common.adminStats': 'ADMIN STATS',
    'admin.common.adminSince': 'Admin since',
    'admin.common.accessLevel': 'Access level',
    'admin.common.fullAccess': 'Full Access',
    'admin.common.signOut': 'Sign Out',
    'admin.common.me': 'ME',
    
    // Artists Page
    'artists.title': 'Gospel Artists',
    'artists.subtitle': 'Discover gospel artists from around the world. Explore their music, learn about their journey, and find chord charts for their most popular songs.',
    'artists.searchPlaceholder': 'Search artists, genres, or countries...',
    'artists.artists': 'Artists',
    'artists.countries': 'Countries',
    'artists.songs': 'Songs',
    'artists.avgRating': 'Avg Rating',
    'artists.allArtists': 'All Artists',
    'artists.searchResults': 'Search Results for',
    'artists.loading': 'Loading artists...',
    'artists.loadingDb': 'Loading artists from database...',
    'artists.noArtists': 'No artists found',
    'artists.tryAdjusting': 'Try adjusting your search terms',
    'artists.noArtistsDb': 'No artists in the database yet',
    'artists.viewSongs': 'View Songs',
    'artists.loadMore': 'Load More Artists',
    'artists.remaining': 'remaining',
    'artists.genre': 'Genre',
    'artists.founded': 'Founded',
    'artists.backToArtists': 'Back to Artists',
    'artists.artistNotFound': 'Artist Not Found',
    'artists.artistNotFoundDesc': 'The artist you\'re looking for doesn\'t exist.',
    'artists.songsBy': 'Songs by',
    'artists.exploreSongs': 'Explore all songs from this artist with chord charts and resources',
    'artists.searchSongs': 'Search songs by title or key...',
    'artists.viewFullSong': 'View Full Song',
    'artists.noSongsFound': 'No songs found',
    'artists.tryAdjustingSearch': 'Try adjusting your search terms.',
    'artists.loadingSongs': 'Loading songs...',
    'artists.songsCount': 'Songs',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcomeBack': 'Welcome back, {name}!',
    'dashboard.welcomeDescription': 'Manage your profile, view your activity, and access your saved content.',
    'dashboard.navigation': 'Navigation',
    'dashboard.overview': 'Overview',
    'dashboard.favorites': 'Favorites',
    'dashboard.downloads': 'Downloads',
    'dashboard.activity': 'Activity',
    'dashboard.profile': 'Profile',
    'dashboard.settings': 'Settings',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.yourStats': 'Your Stats',
    'dashboard.memberSince': 'Member since',
    'dashboard.accountStatus': 'Account status',
    'dashboard.active': 'Active',
    'dashboard.signOut': 'Sign Out',
    'dashboard.yourStatistics': 'Your Statistics',
    'dashboard.realTimeUpdates': 'Real-time updates of your activity on Chord Finder',
    'dashboard.refreshData': 'Refresh Data',
    'dashboard.updating': 'Updating...',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.latestInteractions': 'Your latest interactions with Chord Finder',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.startExploring': 'Start exploring to see your activity here',
    'dashboard.commonTasks': 'Common tasks and shortcuts',
    'dashboard.browseSongs': 'Browse Songs',
    'dashboard.myFavorites': 'My Favorites',
    'dashboard.myDownloads': 'My Downloads',
    'dashboard.browseResources': 'Browse Resources',
    'dashboard.requestSong': 'Request a Song',
    'dashboard.profileInformation': 'Profile Information',
    'dashboard.managePersonalInfo': 'Manage your personal information and preferences',
    'dashboard.editProfile': 'Edit Profile',
    'dashboard.saveChanges': 'Save Changes',
    'dashboard.saving': 'Saving...',
    'dashboard.cancel': 'Cancel',
    'dashboard.firstName': 'First Name',
    'dashboard.lastName': 'Last Name',
    'dashboard.email': 'Email',
    'dashboard.activityHistory': 'Activity History',
    'dashboard.trackEngagement': 'Track your engagement with Chord Finder',
    'dashboard.refresh': 'Refresh',
    'dashboard.noActivityYet': 'No Activity Yet',
    'dashboard.viewResources': 'View Resources',
    'dashboard.preferences': 'Preferences',
    'dashboard.customizeExperience': 'Customize your Chord Finder experience',
    'dashboard.language': 'Language',
    'dashboard.chooseLanguage': 'Choose your preferred language',
    'dashboard.theme': 'Theme',
    'dashboard.chooseTheme': 'Choose your preferred theme',
    'dashboard.notifications': 'Notifications',
    'dashboard.receiveEmailNotifications': 'Receive email notifications',
    'dashboard.accountActions': 'Account Actions',
    'dashboard.manageAccountSettings': 'Manage your account settings',
    'dashboard.password': 'Password',
    'dashboard.changePassword': 'Change Password',
    'dashboard.exportData': 'Export Data',
    'dashboard.yourFavorites': 'Your Favorite Songs',
    'dashboard.songsSavedForAccess': 'Songs you\'ve saved for easy access',
    'dashboard.searchFavorites': 'Search your favorite songs...',
    'dashboard.totalFavorites': 'Total Favorites',
    'dashboard.genres': 'Genres',
    'dashboard.addedThisWeek': 'Added This Week',
    'dashboard.loadingFavorites': 'Loading your favorite songs...',
    'dashboard.viewChords': 'View Chords',
    'dashboard.play': 'Play',
    'dashboard.added': 'Added',
    'dashboard.noFavoritesYet': 'No Favorite Songs Yet',
    'dashboard.startExploringSongs': 'Start exploring songs and add them to your favorites',
    'dashboard.yourDownloads': 'Your Downloads',
    'dashboard.resourcesForOffline': 'Resources you\'ve downloaded for offline access',
    'dashboard.searchDownloads': 'Search your downloads...',
    'dashboard.allTypes': 'All Types',
    'dashboard.totalDownloads': 'Total Downloads',
    'dashboard.pdfs': 'PDFs',
    'dashboard.categories': 'Categories',
    'dashboard.thisWeek': 'This Week',
    'dashboard.loadingDownloads': 'Loading your downloads...',
    'dashboard.downloaded': 'Downloaded',
    'dashboard.open': 'Open',
    'dashboard.share': 'Share',
    'dashboard.noDownloadsYet': 'No Downloads Yet',
    'dashboard.startExploringResources': 'Start exploring resources and download them for offline access',
    'dashboard.yourActivity': 'Your Activity',
    'dashboard.trackEngagementWithFinder': 'Track your engagement with Chord Finder',
    'dashboard.totalActivities': 'Total Activities',
    'dashboard.ratings': 'Ratings',
    'dashboard.activityTimeline': 'Activity Timeline',
    'dashboard.yourRecentInteractions': 'Your recent interactions with Chord Finder',
    'dashboard.loading': 'Loading...',
    'dashboard.loadingActivity': 'Loading your activity...',
    'dashboard.justNow': 'Just now',
    'dashboard.profileSettings': 'Profile Settings',
    'dashboard.managePersonalInfoAndAccount': 'Manage your personal information and account settings',
    'dashboard.accountInformation': 'Account Information',
    'dashboard.yourAccountDetails': 'Your account details and status',
    'dashboard.emailAddress': 'Email Address',
    'dashboard.manageSettings': 'Manage your settings',
    'dashboard.security': 'Security',
    'dashboard.manageAccountSecurity': 'Manage your account security',
    'dashboard.updateEmail': 'Update Email',
    'dashboard.updateEmailAddress': 'Update your email address',
    'dashboard.dataManagement': 'Data Management',
    'dashboard.manageDataAndAccount': 'Manage your data and account',
    'dashboard.downloadYourData': 'Download your data',
    'dashboard.deleteAccount': 'Delete Account',
    'dashboard.permanentlyDeleteAccount': 'Permanently delete your account',
    'dashboard.emailNotifications': 'Email Notifications',
    'dashboard.pushNotifications': 'Push Notifications',
    'dashboard.receivePushNotifications': 'Receive push notifications',
    'dashboard.autoSave': 'Auto-save',
    'dashboard.automaticallySaveWork': 'Automatically save your work',
    'dashboard.showTutorials': 'Show Tutorials',
    'dashboard.displayHelpfulTutorials': 'Display helpful tutorials',
    'dashboard.firstNameRequired': 'First name is required',
    'dashboard.lastNameRequired': 'Last name is required',
    'dashboard.emailRequired': 'Email is required',
    'dashboard.validEmailRequired': 'Please enter a valid email address',
    'dashboard.failedToUpdateProfile': 'Failed to update profile. Please try again.',
    
    // Song Detail Page
    'songDetail.loading': 'Loading song details...',
    'songDetail.notFound': 'Song not found',
    'songDetail.slug': 'Song slug',
    'songDetail.error': 'Error',
    'songDetail.backToSongs': 'Back to Songs',
    'songDetail.artist': 'Artist',
    'songDetail.language': 'Language',
    'songDetail.difficulty': 'Difficulty',
    'songDetail.key': 'Key',
    'songDetail.tempo': 'Tempo',
    'songDetail.year': 'Year',
    'songDetail.category': 'Category',
    'songDetail.lyrics': 'Lyrics',
    'songDetail.chords': 'Chords',
    'songDetail.audio': 'Audio',
    'songDetail.video': 'Video',
    'songDetail.download': 'Download',
    'songDetail.share': 'Share',
    'songDetail.followAlong': 'Follow along with the chords and lyrics below',
    'songDetail.linesAdded': 'Lyrics and chords added by administrator • {lines} lines',
    'songDetail.noLyrics': 'No lyrics added yet',
    'songDetail.adminNeedsToAdd': 'An administrator needs to add the lyrics and chords for this song in the admin dashboard.',
    'songDetail.adminDashboard': 'Admin Dashboard → Songs → Edit → Add Lyrics',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.songs': 'Chansons',
    'nav.chords': 'Accords',
    'nav.resources': 'Ressources',
    'nav.about': 'À propos',
    'nav.admin': 'Admin',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.dashboard': 'Tableau de bord',
    'nav.logout': 'Déconnexion',
    'nav.contact': 'Contact',
    
    // Login & Register
    'auth.signIn': 'Se connecter',
    'auth.signInTitle': 'Connectez-vous à votre compte',
    'auth.welcomeBack': 'Bon retour',
    'auth.signInDescription': 'Entrez votre email et votre mot de passe pour accéder à votre compte',
    'auth.signingIn': 'Connexion en cours...',
    'auth.signUp': 'S\'inscrire',
    'auth.signUpTitle': 'Créez Votre Compte',
    'auth.signUpDescription': 'Entrez vos informations pour créer votre compte et commencer votre voyage musical',
    'auth.createAccount': 'Créer un compte',
    'auth.createAccountTitle': 'Créez votre compte',
    'auth.startJourney': 'Commencez votre voyage musical aujourd\'hui',
    'auth.createAccountDescription': 'Entrez vos informations pour créer votre compte',
    'auth.creatingAccount': 'Création du compte...',
    'auth.getStarted': 'Commencer',
    'auth.dontHaveAccount': 'Vous n\'avez pas de compte?',
    'auth.alreadyHaveAccount': 'Vous avez déjà un compte?',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.firstName': 'Prénom',
    'auth.lastName': 'Nom',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.backToHome': 'Retour à l\'accueil',
    'auth.enterEmail': 'Entrez votre email',
    'auth.enterPassword': 'Entrez votre mot de passe',
    'auth.createPassword': 'Créez un mot de passe',
    'auth.confirmYourPassword': 'Confirmez votre mot de passe',
    'auth.fillAllFields': 'Veuillez remplir tous les champs',
    'auth.invalidEmailPassword': 'Email ou mot de passe invalide. Veuillez vérifier vos identifiants et réessayer.',
    'auth.loginFailed': 'Échec de la connexion. Veuillez réessayer.',
    'auth.passwordsDoNotMatch': 'Les mots de passe ne correspondent pas',
    'auth.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.invalidEmail': 'Veuillez entrer une adresse email valide',
    'auth.registrationFailed': 'Échec de l\'inscription. Veuillez vérifier vos informations et réessayer.',
    'auth.welcomeToPhinAccords': 'Bienvenue sur PhinAccords',
    'auth.joinMusicians': 'Rejoignez des milliers de musiciens et de chefs de culte qui utilisent notre plateforme pour découvrir et apprendre les accords de musique gospel.',
    'auth.accessChords': 'Accédez à des milliers de grilles d\'accords',
    'auth.interactiveDiagrams': 'Diagrammes interactifs de piano et de guitare',
    'auth.saveFavorites': 'Enregistrez vos chansons et accords préférés',
    'auth.builtBy': 'Créé par',
    
    // 404 Not Found
    'notFound.title': '404 - Page Non Trouvée',
    'notFound.description': 'La page que vous recherchez n\'existe pas ou a été déplacée.',
    'notFound.message': 'Ne vous inquiétez pas, même les meilleurs musiciens jouent parfois une fausse note. Remettons-nous à la musique !',
    'notFound.goHome': 'Retour à l\'Accueil',
    'notFound.browseSongs': 'Parcourir les Chansons',
    'notFound.goBack': 'Retour',
    'notFound.popularPages': 'Pages Populaires',
    'notFound.songs': 'Chansons',
    'notFound.pianoChords': 'Accords de Piano',
    'notFound.guitarChords': 'Accords de Guitare',
    'notFound.artists': 'Artistes',
    'notFound.resources': 'Ressources',
    
    // Common
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.clear': 'Effacer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.view': 'Voir',
    'common.download': 'Télécharger',
    'common.share': 'Partager',
    'common.favorite': 'Favori',
    'common.favorites': 'Favoris',
    'common.profile': 'Profil',
    'common.downloads': 'Téléchargements',
    'common.rating': 'Note',
    'common.difficulty': 'Difficulté',
    'common.key': 'Tonalité',
    'common.tempo': 'Tempo',
    'common.artist': 'Artiste',
    'common.category': 'Catégorie',
    'common.year': 'Année',
    'common.genre': 'Genre',
    'common.tags': 'Étiquettes',
    'common.description': 'Description',
    'common.lyrics': 'Paroles',
    'common.chords': 'Accords',
    'common.chordChart': 'Grille d\'accords',
    'common.chordProgression': 'Progression d\'accords',
    'common.transpose': 'Transposer',
    'common.originalKey': 'Tonalité originale',
    'common.currentKey': 'Tonalité actuelle',
    'common.capo': 'Capodastre',
    'common.strummingPattern': 'Motif de grattage',
    'common.timeSignature': 'Signature rythmique',
    'common.website': 'Site Web',
    'common.ago': 'il y a',
    'common.document': 'Document',
    'common.image': 'Image',
    'common.video': 'Vidéo',
    'common.audio': 'Audio',
    'common.user': 'Utilisateur',
    'common.bpm': 'BPM',
    'song.rateThisSong': 'Noter cette chanson',
    'song.youRatedThis': 'Vous avez noté cette chanson',
    'song.clickToRemoveRating': 'Cliquez pour supprimer la note',
    'song.addComment': 'Ajouter un commentaire',
    'song.hideComment': 'Masquer le commentaire',
    'song.comment': 'Commentaire',
    'song.submitComment': 'Soumettre le commentaire',
    'song.recentRatings': 'Notes récentes',
    'song.averageRating': 'Note moyenne',
    'song.totalRatings': 'Total des notes',
    'song.favoriteSongs': 'Chansons favorites',
    'song.songsYouveSaved': 'Chansons que vous avez sauvegardées',
    'song.downloads': 'Téléchargements',
    'song.resourcesDownloaded': 'Ressources téléchargées',
    'song.ratingsGiven': 'Notes données',
    'song.songsYouveRated': 'Chansons que vous avez notées',
    'song.memberSince': 'Membre depuis',
    'song.daysAgo': 'jours',
    
    // Chords
    'chord.piano': 'Piano',
    'chord.allKeys': 'Toutes les tonalités',
    'chord.allLevels': 'Tous les niveaux',
    'chord.easy': 'Facile',
    'chord.medium': 'Moyen',
    'chord.hard': 'Difficile',
    'chord.commonUses': 'Utilisations courantes',
    'chord.alsoKnownAs': 'Aussi connu sous le nom de',
    'chord.handPositionGuide': 'Guide de position des mains',
    'chord.techniqueTips': 'Conseils techniques',
    'chord.practice': 'Pratique',
    'chord.finger': 'Doigt',
    'chord.pianoTechnique': 'Gardez vos doigts courbés, appuyez fermement mais sans tension, et maintenez une position de poignet détendue.',
    
    // French chord names
    'chord.C': 'Do',
    'chord.C#': 'Do#',
    'chord.Db': 'Ré♭',
    'chord.D': 'Ré',
    'chord.D#': 'Ré#',
    'chord.Eb': 'Mi♭',
    'chord.E': 'Mi',
    'chord.F': 'Fa',
    'chord.F#': 'Fa#',
    'chord.Gb': 'Sol♭',
    'chord.G': 'Sol',
    'chord.G#': 'Sol#',
    'chord.Ab': 'La♭',
    'chord.A': 'La',
    'chord.A#': 'La#',
    'chord.Bb': 'Si♭',
    'chord.B': 'Si',
    
    // Piano Chords Page
    'piano.title': 'Accords de Piano',
    'piano.subtitle': 'Maîtrisez chaque accord de piano avec des diagrammes interactifs, positions des notes et guides audio. Parfait pour les pianistes de tous niveaux.',
    'piano.chords': 'Accords de Piano',
    'piano.interactive': 'Interactif',
    'piano.diagramsSounds': 'Diagrammes & Sons',
    'piano.learn': 'Apprendre',
    'piano.playPractice': 'Jouer & Pratiquer',
    'piano.loading': 'Chargement des accords de piano...',
    'piano.noChords': 'Aucun accord de piano trouvé',
    'piano.tryAdjusting': 'Essayez d\'ajuster votre recherche ou vos filtres',
    'piano.clearFilters': 'Effacer les Filtres',
    'piano.searchPlaceholder': 'Rechercher des accords...',
    'piano.filterByKey': 'Filtrer par Tonalité',
    'piano.filterByDifficulty': 'Filtrer par Difficulté',
    'piano.advanced': 'Avancé',
    'piano.quickReference': 'Référence Rapide',
    'piano.essentialProgressions': 'Progressions d\'accords essentielles et motifs courants',
    'piano.commonProgressions': 'Progressions Courantes',
    'piano.jazzProgressions': 'Progressions Jazz',
    'piano.pianoTechniques': 'Techniques de Piano',
    'piano.inversions': 'Renversements',
    'piano.voicings': 'Voix',
    'piano.progressions': 'Progressions',
    'piano.openClosed': 'Ouvert & Fermé',
    'piano.commonPatterns': 'Motifs Courants',
    'piano.category': 'Catégorie',
    'piano.sortBy': 'Trier par',
    'piano.allCategories': 'Toutes les Catégories',
    'piano.major': 'Majeur',
    'piano.minor': 'Mineur',
    'piano.seventh': 'Accords de 7e',
    'piano.suspended': 'Suspendu',
    'piano.name': 'Nom',
    'piano.popularity': 'Popularité',
    
    // Keys
    'piano.key.C': 'Do',
    'piano.key.C#': 'Do#',
    'piano.key.Db': 'Ré♭',
    'piano.key.D': 'Ré',
    'piano.key.D#': 'Ré#',
    'piano.key.Eb': 'Mi♭',
    'piano.key.E': 'Mi',
    'piano.key.F': 'Fa',
    'piano.key.F#': 'Fa#',
    'piano.key.Gb': 'Sol♭',
    'piano.key.G': 'Sol',
    'piano.key.G#': 'Sol#',
    'piano.key.Ab': 'La♭',
    'piano.key.A': 'La',
    'piano.key.A#': 'La#',
    'piano.key.Bb': 'Si♭',
    'piano.key.B': 'Si',
    
    
    // Hero Section
    'hero.badge': 'Ressources de Musique Gospel',
    'hero.title': 'Trouvez les Accords de Musique Gospel & Ressources',
    'hero.subtitle': 'Découvrez les grilles d\'accords, paroles et ressources pour votre ministère d\'adoration. Soutenir les passionnés de musique gospel avec des collections organisées et des progressions d\'accords faciles à suivre.',
    'hero.searchPlaceholder': 'Rechercher des chansons, artistes, accords ou paroles...',
    'hero.browseSongs': 'Parcourir les Chansons',
    'hero.requestSong': 'Demander une Chanson',
    
    // Footer
    'footer.description': 'Découvrez les accords de musique gospel, paroles et ressources pour l\'adoration.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.resources': 'Ressources',
    'footer.allResources': 'Toutes les Ressources',
    'footer.learning': 'Apprentissage',
    'footer.community': 'Communauté',
    'footer.contact': 'Contact',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    
    // About Page
    'about.title': 'À Propos de PhinAccords',
    'about.subtitle': 'Faire de n\'importe qui un adorateur accompli au piano, formé à exceller dans le service et à demeurer connecté à l\'Esprit Saint.',
    'about.exploreSongs': 'Explorer les Chansons',
    'about.joinCommunity': 'Rejoindre la Communauté',
    'about.missionTitle': 'Notre Mission',
    'about.missionText1': 'PhinAccords a une vision : faire de n\'importe qui un adorateur au piano. Notre mission est d\'équiper et de transformer les passionnés de musique en des musiciens capables de servir Dieu avec efficacité et excellence, en les guidant dans la maîtrise des accords et dans une adoration spirituelle authentique.',
    'about.missionText2': 'Cette mission est motivée par deux convictions :',
    'about.missionDistinctionTitle': 'La Distinction Spirituelle et l\'Adoration Pure',
    'about.missionDistinctionText': 'Nous avons remarqué que la majorité des plateformes d\'apprentissage se concentre sur des chants séculiers. Or, l\'Écriture nous appelle à la distinction :',
    'about.missionEfficiencyTitle': 'L\'Accès Facile et l\'Efficacité du Service',
    'about.missionEfficiencyText': 'Nous résolvons les problèmes pratiques qui freinent les musiciens : la difficulté à trouver des grilles d\'accords chrétiennes précises, l\'éparpillement des informations (WhatsApp, etc.), et l\'attente des mentors.',
    'about.missionResources': 'De plus, nous fournirons au fur et à mesure des ressources essentielles pour aller au-delà des accords, couvrant : comment jouer, comment se préparer à servir à un culte, qu\'est-ce qu\'être un adorateur au piano, et bien plus.',
    'about.missionConclusion': 'PhinAccords résout tout cela. N\'importe qui peut commencer son parcours, accéder instantanément à des grilles d\'accords complètes, et apprendre à jouer du piano pour devenir un instrument d\'adoration efficace dans son église ou sa communauté.',
    'about.versesDistinctionTitle': 'Distinction et Sainteté',
    'about.versesServiceTitle': 'Excellence dans le Service',
    'about.verse1': '« Quel rapport y a-t-il entre la justice et l\'iniquité ? Ou qu\'y a-t-il de commun entre la lumière et les ténèbres ? »',
    'about.verse1Ref': '(2 Corinthiens 6:14, LSG)',
    'about.verse2': '« Ayez du zèle, et non de la paresse. Soyez fervents d\'esprit, servez le Seigneur. »',
    'about.verse2Ref': '(Romains 12:11, LSG)',
    'about.verse3': '« Car nous sommes le temple du Dieu vivant… C\'est pourquoi, sortez du milieu d\'eux, et séparez-vous, dit le Seigneur. »',
    'about.verse3Ref': '(2 Corinthiens 6:16-17, LSG)',
    'about.verse4': '« Fais l\'œuvre d\'un évangéliste, remplis bien ton ministère. »',
    'about.verse4Ref': '(2 Timothée 4:5, LSG)',
    'about.verse5': '« Ne participez pas aux œuvres stériles des ténèbres, mais démasquez-les plutôt. »',
    'about.verse5Ref': '(Éphésiens 5:11, LSG)',
    'about.verse6': '« Travaillons de mieux en mieux à l\'œuvre du Seigneur, sachant que notre travail n\'est pas sans résultat dans le Seigneur. »',
    'about.verse6Ref': '(1 Corinthiens 15:58, LSG)',
    'about.versesConclusion': 'Nous choisissons clairement de marcher dans la lumière en fournissant exclusivement des ressources basées sur le répertoire gospel et d\'adoration chrétienne.',
    'about.getStarted': 'Commencer',
    'about.valuesTitle': 'Nos Valeurs',
    'about.valuesSubtitle': 'Les principes qui guident tout ce que nous faisons',
    'about.musicalExcellence': 'Ministère et Adoration Authentique',
    'about.musicalExcellenceDesc': 'Notre plateforme est un espace pour développer la maîtrise des accords tout en demeurant connecté à l\'Esprit Saint et en servant le ministère avec ferveur.',
    'about.passionateMinistry': 'Ressources Gospel Ciblées (Lumière et Distinction)',
    'about.passionateMinistryDesc': 'Nous fournissons exclusivement des grilles d\'accords et des ressources d\'adoration de haute qualité et précises pour le répertoire chrétien, en évitant toute confusion entre la lumière et les ténèbres.',
    'about.communitySupport': 'Service Efficace et Excellence',
    'about.communitySupportDesc': 'Nous permettons aux musiciens de servir Dieu avec efficacité et excellence, en leur donnant les outils pour exceller dans le ministère et être toujours prêts.',
    'about.qualityResources': 'Soutien Communautaire',
    'about.qualityResourcesDesc': 'Nous visons à bâtir et soutenir les communautés d\'adoration pour équiper n\'importe qui et faire de lui un adorateur accompli au piano.',
    
    // Contact Page
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Vous avez une question, une suggestion ou besoin d\'aide ? Nous serions ravis de vous entendre.',
    'contact.ourLocation': 'Notre Localisation',
    'contact.location': 'Gatineau, Canada',
    'contact.sendMessage': 'Envoyez-nous un Message',
    'contact.formDescription': 'Remplissez le formulaire ci-dessous et nous vous répondrons dès que possible.',
    'contact.fullName': 'Nom Complet',
    'contact.emailAddress': 'Adresse Email',
    'contact.inquiryType': 'Type de Demande',
    'contact.selectInquiryType': 'Sélectionner le type de demande',
    'contact.generalInquiry': 'Demande Générale',
    'contact.songRequest': 'Demande de Chanson',
    'contact.technicalSupport': 'Support Technique',
    'contact.partnership': 'Partenariat',
    'contact.feedback': 'Commentaires',
    'contact.other': 'Autre',
    'contact.subject': 'Sujet',
    'contact.briefDescription': 'Brève description de votre demande',
    'contact.message': 'Message',
    'contact.tellUsMore': 'Dites-nous-en plus sur votre demande...',
    'contact.responseTime': 'Temps de Réponse',
    'contact.responseTimeText': 'Nous répondons généralement dans les 24 heures pendant les jours ouvrables.',
    'contact.send': 'Envoyer le Message',
    'contact.sending': 'Envoi en cours...',
    'contact.clearForm': 'Effacer le Formulaire',
    'contact.messageSent': 'Message Envoyé avec Succès !',
    'contact.messageSentText': 'Merci de nous avoir contactés. Nous vous répondrons dans les 24 heures.',
    'contact.sendAnother': 'Envoyer un Autre Message',
    'contact.backToHome': 'Retour à l\'Accueil',
    
    // Resources Page
    'resources.title': 'Explorez Nos Ressources',
    'resources.subtitle': 'Téléchargez des guides, des modèles et des tutoriels pour améliorer votre parcours musical.',
    'resources.categories': 'Catégories',
    'resources.searchPlaceholder': 'Rechercher des ressources...',
    'resources.loading': 'Chargement des ressources...',
    'resources.noResources': 'Aucune ressource trouvée correspondant à vos critères.',
    'resources.loadMore': 'Charger Plus de Ressources',
    'resources.remaining': 'restantes',
    'resources.featuredCollections': 'Collections en Vedette',
    'resources.beginnersBundle': 'Pack Débutant',
    'resources.beginnersBundleDesc': 'Commencez votre parcours avec des guides essentiels et des routines de pratique.',
    'resources.viewCollection': 'Voir la Collection',
    'resources.worshipLeaderPack': 'Pack Chef de Culte',
    'resources.worshipLeaderPackDesc': 'Ressources pour diriger efficacement l\'adoration et gérer l\'équipe.',
    'resources.musiciansToolkit': 'Boîte à Outils du Musicien',
    'resources.musiciansToolkitDesc': 'Théorie avancée, guides techniques et conseils de performance.',
    'resources.joinCommunity': 'Rejoignez Notre Communauté',
    'resources.joinCommunityDesc': 'Connectez-vous avec d\'autres musiciens, partagez vos idées et obtenez du soutien.',
    'resources.joinForum': 'Rejoindre le Forum',
    
    // Artists Page
    'artists.viewMode': 'Mode d\'Affichage',
    'artists.gridView': 'Vue Grille',
    'artists.listView': 'Vue Liste',
    
    // Songs
    'song.loading': 'Chargement des chansons depuis la base de données...',
    'song.noSongs': 'Aucune chanson trouvée',
    'song.comeBack': 'Revenez bientôt pour de nouvelles chansons gospel !',
    'song.viewChords': 'Voir les Accords',
    'song.viewAll': 'Voir Toutes les Chansons',
    
    // Tips Section
    'tips.title': 'Conseils & Ressources',
    'tips.subtitle': 'Améliorez votre ministère d\'adoration avec nos conseils et ressources organisés pour la musique gospel',
    'tips.readingCharts': 'Lire les Grilles d\'Accords',
    'tips.readingChartsDesc': 'Apprenez à lire les grilles d\'accords efficacement. Commencez par les accords majeurs et mineurs de base, puis progressez vers des progressions plus complexes.',
    'tips.transposeSongs': 'Transposer les Chansons',
    'tips.transposeSongsDesc': 'Maîtrisez l\'art de transposer les chansons dans différentes tonalités. Compétence essentielle pour adapter les chansons à votre tessiture ou instrument.',
    'tips.leadingWorship': 'Diriger l\'Adoration',
    'tips.leadingWorshipDesc': 'Conseils pour diriger l\'adoration efficacement. Apprenez sur le flux des chansons, les changements de tonalité et l\'engagement de votre congrégation.',
    'tips.chordProgressions': 'Progressions d\'Accords',
    'tips.chordProgressionsDesc': 'Comprenez les progressions d\'accords gospel communes et comment créer des transitions fluides entre les chansons de votre set.',
    'tips.category.beginner': 'Débutant',
    'tips.category.intermediate': 'Intermédiaire',
    'tips.category.advanced': 'Avancé',
    'tips.moreResources': 'Plus de ressources à venir bientôt de Heavenkeys Ltd.',
    
    // Admin
    // Admin Dashboard (French)
    'admin.dashboard.title': 'Tableau de Bord Admin',
    'admin.dashboard.subtitle': 'Gérez votre collection d\'accords et les paramètres de l\'application.',
    'admin.dashboard.overview': 'Vue d\'ensemble',
    'admin.dashboard.analytics': 'Analytiques',
    'admin.dashboard.activity': 'Activité',
    'admin.dashboard.settings': 'Paramètres',
    'admin.dashboard.systemStatistics': 'Statistiques Système',
    'admin.dashboard.systemStatisticsDesc': 'Mises à jour en temps réel des performances de votre plateforme',
    'admin.dashboard.refreshData': 'Actualiser les Données',
    'admin.dashboard.updating': 'Mise à jour...',
    'admin.dashboard.songsInCollection': 'Chansons dans la Collection',
    'admin.dashboard.totalSongsAvailable': 'Total des chansons disponibles',
    'admin.dashboard.artists': 'Artistes',
    'admin.dashboard.artistsInDatabase': 'Artistes dans la base de données',
    'admin.dashboard.resources': 'Ressources',
    'admin.dashboard.learningResources': 'Ressources d\'apprentissage',
    'admin.dashboard.activeUsers': 'Utilisateurs Actifs',
    'admin.dashboard.currentlyActive': 'Actuellement actifs',
    'admin.dashboard.recentActivity': 'Activité Récente',
    'admin.dashboard.latestSystemActivities': 'Dernières activités système et changements',
    'admin.dashboard.noRecentActivity': 'Aucune activité récente',
    'admin.dashboard.systemActivitiesWillAppear': 'Les activités système apparaîtront ici',
    'admin.dashboard.quickActions': 'Actions Rapides',
    'admin.dashboard.commonAdminTasks': 'Tâches d\'administration courantes et raccourcis',
    'admin.dashboard.manageSongs': 'Gérer les Chansons',
    'admin.dashboard.manageArtists': 'Gérer les Artistes',
    'admin.dashboard.manageUsers': 'Gérer les Utilisateurs',
    'admin.dashboard.manageResources': 'Gérer les Ressources',
    'admin.dashboard.viewAnalytics': 'Voir les Analytiques',
    'admin.dashboard.platformAnalytics': 'Analytiques de la Plateforme',
    'admin.dashboard.comprehensiveInsights': 'Informations complètes sur les performances de votre plateforme',
    'admin.dashboard.totalUsers': 'Total des Utilisateurs',
    'admin.dashboard.collections': 'Collections',
    'admin.dashboard.databaseStatus': 'Statut de la Base de Données',
    'admin.dashboard.connected': 'Connecté',
    'admin.dashboard.lastSync': 'Dernière Synchronisation',
    'admin.dashboard.justNow': 'À l\'instant',
    'admin.dashboard.systemHealth': 'Santé du Système',
    'admin.dashboard.healthy': 'Sain',
    'admin.dashboard.growthRate': 'Taux de Croissance',
    'admin.dashboard.engagement': 'Engagement',
    'admin.dashboard.high': 'Élevé',
    'admin.dashboard.performance': 'Performance',
    'admin.dashboard.excellent': 'Excellent',
    'admin.dashboard.systemActivity': 'Activité Système',
    'admin.dashboard.trackSystemActivities': 'Suivre les activités système et les actions d\'administration',
    'admin.dashboard.refresh': 'Actualiser',
    'admin.dashboard.noActivityYet': 'Aucune Activité Encore',
    'admin.dashboard.systemActivitiesWillAppearHere': 'Les activités système apparaîtront ici',
    'admin.dashboard.systemSettings': 'Paramètres Système',
    'admin.dashboard.configureAdminPanel': 'Configurer votre panneau d\'administration et les préférences système',
    'admin.dashboard.databaseConnection': 'Connexion à la Base de Données',
    'admin.dashboard.manageDatabaseSettings': 'Gérer les paramètres de la base de données',
    'admin.dashboard.systemNotifications': 'Notifications Système',
    'admin.dashboard.receiveAdminAlerts': 'Recevoir des alertes d\'administration',
    'admin.dashboard.configure': 'Configurer',
    'admin.dashboard.backupStatus': 'Statut de Sauvegarde',
    'admin.dashboard.lastBackup': 'Dernière sauvegarde : il y a 2 heures',
    'admin.dashboard.backupNow': 'Sauvegarder Maintenant',
    'admin.dashboard.adminActions': 'Actions d\'Administration',
    'admin.dashboard.systemManagement': 'Gestion et maintenance du système',
    'admin.dashboard.securitySettings': 'Paramètres de Sécurité',
    'admin.dashboard.databaseManagement': 'Gestion de la Base de Données',
    'admin.dashboard.performanceMonitoring': 'Surveillance des Performances',
    'admin.dashboard.systemMaintenance': 'Maintenance Système',
    'admin.activity': 'Activité',
    
    'admin.songs.title': 'Gestion des Chansons',
    'admin.songs.subtitle': 'Gérez votre collection de chansons, modifiez les détails et organisez le contenu',
    'admin.songs.add': 'Ajouter une Chanson',
    'admin.songs.import': 'Importer',
    'admin.songs.search': 'Rechercher des chansons...',
    'admin.songs.allGenres': 'Tous les Genres',
    'admin.songs.totalSongs': 'Total des Chansons',
    'admin.songs.genres': 'Genres',
    'admin.songs.filteredResults': 'Résultats Filtrés',
    'admin.songs.noSongs': 'Aucune chanson trouvée',
    'admin.songs.noSongsFilter': 'Essayez d\'ajuster votre recherche ou vos critères de filtre',
    'admin.songs.noSongsEmpty': 'Commencez par ajouter votre première chanson à la collection',
    'admin.songs.addFirst': 'Ajouter la Première Chanson',
    'admin.songs.created': 'Créé',
    'admin.songs.updated': 'Mis à jour',
    'admin.songs.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette chanson?',
    'admin.songs.deleteSuccess': 'Chanson supprimée avec succès',
    'admin.songs.deleteError': 'Échec de la suppression de la chanson',
    'admin.songs.addTitle': 'Ajouter une Nouvelle Chanson',
    'admin.songs.addDescription': 'Remplissez les détails pour ajouter une nouvelle chanson à votre collection',
    'admin.songs.titleLabel': 'Titre *',
    'admin.songs.titlePlaceholder': 'Entrez le titre de la chanson',
    'admin.songs.artistLabel': 'Artiste *',
    'admin.songs.selectArtist': 'Sélectionner un artiste',
    'admin.songs.newArtist': 'Ajouter un Nouvel Artiste',
    'admin.songs.newArtistName': 'Nom du Nouvel Artiste',
    'admin.songs.newArtistPlaceholder': 'Entrez le nom de l\'artiste',
    'admin.songs.keyLabel': 'Tonalité',
    'admin.songs.keyPlaceholder': 'ex. Do',
    'admin.songs.tempoLabel': 'Tempo (BPM)',
    'admin.songs.tempoPlaceholder': 'ex. 120',
    'admin.songs.lyricsLabel': 'Paroles',
    'admin.songs.lyricsPlaceholder': 'Entrez les paroles de la chanson...',
    'admin.songs.cancel': 'Annuler',
    'admin.songs.addSuccess': 'Chanson ajoutée avec succès',
    'admin.songs.addError': 'Échec de l\'ajout de la chanson',
    'admin.songs.requiredFields': 'Veuillez remplir le titre et l\'artiste',
    'admin.songs.artistCreated': 'Nouvel artiste créé avec succès',
    'admin.songs.artistError': 'Échec de la création de l\'artiste',
    
    // Artists Page
    'artists.title': 'Artistes Gospel',
    'artists.subtitle': 'Découvrez des artistes gospel du monde entier. Explorez leur musique, apprenez-en plus sur leur parcours et trouvez des grilles d\'accords pour leurs chansons les plus populaires.',
    'artists.searchPlaceholder': 'Rechercher des artistes, genres ou pays...',
    'artists.artists': 'Artistes',
    'artists.countries': 'Pays',
    'artists.songs': 'Chansons',
    'artists.avgRating': 'Note Moyenne',
    'artists.allArtists': 'Tous les Artistes',
    'artists.searchResults': 'Résultats de recherche pour',
    'artists.loading': 'Chargement des artistes...',
    'artists.loadingDb': 'Chargement des artistes depuis la base de données...',
    'artists.noArtists': 'Aucun artiste trouvé',
    'artists.tryAdjusting': 'Essayez d\'ajuster vos termes de recherche',
    'artists.noArtistsDb': 'Aucun artiste dans la base de données pour le moment',
    'artists.viewSongs': 'Voir les Chansons',
    'artists.loadMore': 'Charger Plus d\'Artistes',
    'artists.remaining': 'restants',
    'artists.genre': 'Genre',
    'artists.founded': 'Fondé',
    'artists.backToArtists': 'Retour aux Artistes',
    'artists.artistNotFound': 'Artiste Non Trouvé',
    'artists.artistNotFoundDesc': 'L\'artiste que vous recherchez n\'existe pas.',
    'artists.songsBy': 'Chansons par',
    'artists.exploreSongs': 'Explorez toutes les chansons de cet artiste avec des grilles d\'accords et des ressources',
    'artists.searchSongs': 'Rechercher des chansons par titre ou tonalité...',
    'artists.viewFullSong': 'Voir la Chanson Complète',
    'artists.noSongsFound': 'Aucune chanson trouvée',
    'artists.tryAdjustingSearch': 'Essayez d\'ajuster vos termes de recherche.',
    'artists.loadingSongs': 'Chargement des chansons...',
    'artists.songsCount': 'Chansons',
    
    // Songs Page
    'songs.title': 'Chansons Gospel',
    'songs.subtitle': 'Découvrez de belles chansons gospel avec grilles d\'accords, paroles et ressources pour l\'adoration',
    'songs.searchPlaceholder': 'Rechercher des chansons, artistes, accords ou paroles...',
    'songs.allSongs': 'Toutes les Chansons Gospel',
    'songs.searchResults': 'Résultats de recherche',
    'songs.songsFound': 'chansons trouvées',
    'songs.loading': 'Chargement des chansons...',
    'songs.fetching': 'Récupération des dernières chansons gospel de notre collection',
    'songs.noSongs': 'Aucune chanson dans la base de données',
    'songs.adminNeedsToAdd': 'L\'administrateur doit d\'abord ajouter des chansons à la base de données.',
    'songs.noSongsFound': 'Aucune chanson trouvée',
    'songs.tryAdjusting': 'Essayez d\'ajuster vos termes de recherche ou parcourez toutes les chansons.',
    'songs.clearFilters': 'Effacer les Filtres',
    'songs.loadMore': 'Charger Plus de Chansons',
    'songs.remaining': 'restantes',
    'songs.browseCollection': 'Parcourez notre collection complète de chansons gospel avec grilles d\'accords et ressources',
    'songs.songsAvailable': 'chansons disponibles',
    'songs.fromDatabase': 'De notre collection de base de données',
    'songs.allCategories': 'Toutes les Chansons',
    'songs.classicHymn': 'Hymne Classique',
    'songs.contemporary': 'Contemporain',
    'songs.modernHymn': 'Hymne Moderne',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.welcomeBack': 'Bon retour, {name} !',
    'dashboard.welcomeDescription': 'Gérez votre profil, consultez votre activité et accédez à votre contenu enregistré.',
    'dashboard.navigation': 'Navigation',
    'dashboard.overview': 'Vue d\'ensemble',
    'dashboard.favorites': 'Favoris',
    'dashboard.downloads': 'Téléchargements',
    'dashboard.activity': 'Activité',
    'dashboard.profile': 'Profil',
    'dashboard.settings': 'Paramètres',
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.yourStats': 'Vos Statistiques',
    'dashboard.memberSince': 'Membre depuis',
    'dashboard.accountStatus': 'Statut du compte',
    'dashboard.active': 'Actif',
    'dashboard.signOut': 'Déconnexion',
    'dashboard.yourStatistics': 'Vos Statistiques',
    'dashboard.realTimeUpdates': 'Mises à jour en temps réel de votre activité sur Chord Finder',
    'dashboard.refreshData': 'Actualiser les Données',
    'dashboard.updating': 'Mise à jour...',
    'dashboard.recentActivity': 'Activité Récente',
    'dashboard.latestInteractions': 'Vos dernières interactions avec Chord Finder',
    'dashboard.noRecentActivity': 'Aucune activité récente',
    'dashboard.startExploring': 'Commencez à explorer pour voir votre activité ici',
    'dashboard.commonTasks': 'Tâches communes et raccourcis',
    'dashboard.browseSongs': 'Parcourir les Chansons',
    'dashboard.myFavorites': 'Mes Favoris',
    'dashboard.myDownloads': 'Mes Téléchargements',
    'dashboard.browseResources': 'Parcourir les Ressources',
    'dashboard.requestSong': 'Demander une Chanson',
    'dashboard.profileInformation': 'Informations sur le Profil',
    'dashboard.managePersonalInfo': 'Gérez vos informations personnelles et préférences',
    'dashboard.editProfile': 'Modifier le Profil',
    'dashboard.saveChanges': 'Enregistrer les Modifications',
    'dashboard.saving': 'Enregistrement...',
    'dashboard.cancel': 'Annuler',
    'dashboard.firstName': 'Prénom',
    'dashboard.lastName': 'Nom',
    'dashboard.email': 'Email',
    'dashboard.activityHistory': 'Historique des Activités',
    'dashboard.trackEngagement': 'Suivez votre engagement avec Chord Finder',
    'dashboard.refresh': 'Actualiser',
    'dashboard.noActivityYet': 'Aucune Activité Encore',
    'dashboard.viewResources': 'Voir les Ressources',
    'dashboard.preferences': 'Préférences',
    'dashboard.customizeExperience': 'Personnalisez votre expérience Chord Finder',
    'dashboard.language': 'Langue',
    'dashboard.chooseLanguage': 'Choisissez votre langue préférée',
    'dashboard.theme': 'Thème',
    'dashboard.chooseTheme': 'Choisissez votre thème préféré',
    'dashboard.notifications': 'Notifications',
    'dashboard.receiveEmailNotifications': 'Recevoir les notifications par email',
    'dashboard.accountActions': 'Actions du Compte',
    'dashboard.manageAccountSettings': 'Gérez les paramètres de votre compte',
    'dashboard.password': 'Mot de Passe',
    'dashboard.changePassword': 'Changer le Mot de Passe',
    'dashboard.exportData': 'Exporter les Données',
    'dashboard.yourFavorites': 'Vos Chansons Favorites',
    'dashboard.songsSavedForAccess': 'Chansons que vous avez enregistrées pour un accès facile',
    'dashboard.searchFavorites': 'Rechercher vos chansons favorites...',
    'dashboard.totalFavorites': 'Total des Favoris',
    'dashboard.genres': 'Genres',
    'dashboard.addedThisWeek': 'Ajoutés Cette Semaine',
    'dashboard.loadingFavorites': 'Chargement de vos chansons favorites...',
    'dashboard.viewChords': 'Voir les Accords',
    'dashboard.play': 'Jouer',
    'dashboard.added': 'Ajouté',
    'dashboard.noFavoritesYet': 'Aucune Chanson Favorite Encore',
    'dashboard.startExploringSongs': 'Commencez à explorer les chansons et ajoutez-les à vos favoris',
    'dashboard.yourDownloads': 'Vos Téléchargements',
    'dashboard.resourcesForOffline': 'Ressources que vous avez téléchargées pour un accès hors ligne',
    'dashboard.searchDownloads': 'Rechercher vos téléchargements...',
    'dashboard.allTypes': 'Tous les Types',
    'dashboard.totalDownloads': 'Total des Téléchargements',
    'dashboard.pdfs': 'PDFs',
    'dashboard.categories': 'Catégories',
    'dashboard.thisWeek': 'Cette Semaine',
    'dashboard.loadingDownloads': 'Chargement de vos téléchargements...',
    'dashboard.downloaded': 'Téléchargé',
    'dashboard.open': 'Ouvrir',
    'dashboard.share': 'Partager',
    'dashboard.noDownloadsYet': 'Aucun Téléchargement Encore',
    'dashboard.startExploringResources': 'Commencez à explorer les ressources et téléchargez-les pour un accès hors ligne',
    'dashboard.yourActivity': 'Votre Activité',
    'dashboard.trackEngagementWithFinder': 'Suivez votre engagement avec Chord Finder',
    'dashboard.totalActivities': 'Total des Activités',
    'dashboard.ratings': 'Notes',
    'dashboard.activityTimeline': 'Chronologie des Activités',
    'dashboard.yourRecentInteractions': 'Vos interactions récentes avec Chord Finder',
    'dashboard.loading': 'Chargement...',
    'dashboard.loadingActivity': 'Chargement de votre activité...',
    'dashboard.justNow': 'À l\'instant',
    'dashboard.profileSettings': 'Paramètres du Profil',
    'dashboard.managePersonalInfoAndAccount': 'Gérez vos informations personnelles et les paramètres de votre compte',
    'dashboard.accountInformation': 'Informations du Compte',
    'dashboard.yourAccountDetails': 'Les détails et le statut de votre compte',
    'dashboard.emailAddress': 'Adresse Email',
    'dashboard.manageSettings': 'Gérez vos paramètres',
    'dashboard.security': 'Sécurité',
    'dashboard.manageAccountSecurity': 'Gérez la sécurité de votre compte',
    'dashboard.updateEmail': 'Mettre à jour l\'Email',
    'dashboard.updateEmailAddress': 'Mettre à jour votre adresse email',
    'dashboard.dataManagement': 'Gestion des Données',
    'dashboard.manageDataAndAccount': 'Gérez vos données et votre compte',
    'dashboard.downloadYourData': 'Télécharger vos données',
    'dashboard.deleteAccount': 'Supprimer le Compte',
    'dashboard.permanentlyDeleteAccount': 'Supprimer définitivement votre compte',
    'dashboard.emailNotifications': 'Notifications Email',
    'dashboard.pushNotifications': 'Notifications Push',
    'dashboard.receivePushNotifications': 'Recevoir les notifications push',
    'dashboard.autoSave': 'Enregistrement Automatique',
    'dashboard.automaticallySaveWork': 'Enregistrer automatiquement votre travail',
    'dashboard.showTutorials': 'Afficher les Tutoriels',
    'dashboard.displayHelpfulTutorials': 'Afficher les tutoriels utiles',
    'dashboard.firstNameRequired': 'Le prénom est requis',
    'dashboard.lastNameRequired': 'Le nom est requis',
    'dashboard.emailRequired': 'L\'email est requis',
    'dashboard.validEmailRequired': 'Veuillez entrer une adresse email valide',
    'dashboard.failedToUpdateProfile': 'Échec de la mise à jour du profil. Veuillez réessayer.',
    'piano.instrument': 'Instrument',
    'piano.pianoOnly': 'Piano uniquement',
    
    // Song Detail Page
    'songDetail.loading': 'Chargement des détails de la chanson...',
    'songDetail.notFound': 'Chanson introuvable',
    'songDetail.slug': 'Slug de la chanson',
    'songDetail.error': 'Erreur',
    'songDetail.backToSongs': 'Retour aux Chansons',
    'songDetail.artist': 'Artiste',
    'songDetail.language': 'Langue',
    'songDetail.difficulty': 'Difficulté',
    'songDetail.key': 'Tonalité',
    'songDetail.tempo': 'Tempo',
    'songDetail.year': 'Année',
    'songDetail.category': 'Catégorie',
    'songDetail.lyrics': 'Paroles',
    'songDetail.chords': 'Accords',
    'songDetail.audio': 'Audio',
    'songDetail.video': 'Vidéo',
    'songDetail.download': 'Télécharger',
    'songDetail.share': 'Partager',
    'songDetail.followAlong': 'Suivez les accords et paroles ci-dessous',
    'songDetail.linesAdded': 'Paroles et accords ajoutés par l\'administrateur • {lines} lignes',
    'songDetail.noLyrics': 'Aucune parole ajoutée pour le moment',
    'songDetail.adminNeedsToAdd': 'Un administrateur doit ajouter les paroles et accords de cette chanson dans le tableau de bord d\'administration.',
    'songDetail.adminDashboard': 'Tableau de bord Admin → Chansons → Modifier → Ajouter les Paroles',
    
    // Request Song Page
    'requestSong.title': 'Demander une Chanson',
    'requestSong.subtitle': 'Demandez qu\'une chanson soit ajoutée à notre collection',
    'requestSong.songTitle': 'Titre de la Chanson',
    'requestSong.artist': 'Artiste',
    'requestSong.genre': 'Genre',
    'requestSong.key': 'Tonalité',
    'requestSong.difficulty': 'Difficulté',
    'requestSong.description': 'Description',
    'requestSong.contactEmail': 'Email de Contact',
    'requestSong.priority': 'Priorité',
    'requestSong.normal': 'Normale',
    'requestSong.high': 'Haute',
    'requestSong.low': 'Basse',
    'requestSong.submit': 'Soumettre la Demande',
    'requestSong.submitting': 'Envoi en cours...',
    'requestSong.success': 'Demande soumise avec succès !',
    'requestSong.error': 'Échec de la soumission de la demande. Veuillez réessayer.',
    
    // Admin Components
    'admin.editor.titleLabel': 'Titre',
    'admin.editor.artistLabel': 'Artiste',
    'admin.editor.searchArtist': 'Rechercher un artiste...',
    'admin.editor.keySignature': 'Signature de Tonalité',
    'admin.editor.tempoLabel': 'Tempo (BPM)',
    'admin.editor.keyPlaceholder': 'ex. Do, Sol, Lam',
    'admin.editor.tempoPlaceholder': 'ex. 120',
    'admin.editor.lyricsChords': 'Paroles & Accords',
    'admin.editor.formattingGuide': 'Guide de Formatage',
    'admin.editor.useSections': 'Utilisez [Nom de Section] pour les sections (ex. [Couplet 1], [Refrain])',
    'admin.editor.writeChords': 'Écrivez les accords sur leur propre ligne (ex. Do Sol Lam Fa)',
    'admin.editor.useSpaces': 'Utilisez des espaces pour aligner les accords avec les paroles',
    'admin.editor.blankLines': 'Laissez des lignes vides entre les sections pour une meilleure lisibilité',
    'admin.editor.changesVisible': 'Les modifications seront visibles sur la page publique après la sauvegarde',
    'admin.editor.addNewArtist': 'Ajouter un Nouvel Artiste',
    'admin.editor.enterArtistName': 'Entrez le nom de l\'artiste à ajouter à la base de données.',
    'admin.editor.artistName': 'Nom de l\'Artiste',
    'admin.editor.enterArtistNamePlaceholder': 'Entrez le nom de l\'artiste',
    'admin.editor.add': 'Ajouter',
    'admin.editor.cancel': 'Annuler',
    
    // Admin - Users Page
    'admin.users.title': 'Gestion des Utilisateurs',
    'admin.users.subtitle': 'Gérer les utilisateurs, suivre les analyses et surveiller l\'activité des utilisateurs',
    'admin.users.refresh': 'Actualiser',
    'admin.users.exportUsers': 'Exporter les Utilisateurs',
    'admin.users.userManagement': 'Gestion des Utilisateurs',
    'admin.users.analytics': 'Analyses',
    'admin.users.totalUsers': 'Total des Utilisateurs',
    'admin.users.activeUsers': 'Utilisateurs Actifs',
    'admin.users.newThisWeek': 'Nouveaux Cette Semaine',
    'admin.users.onlineNow': 'En Ligne Maintenant',
    'admin.users.searchFilterManage': 'Rechercher, filtrer et gérer vos utilisateurs',
    'admin.users.unknown': 'Inconnu',
    'admin.users.desktop': 'Ordinateur de bureau',
    'admin.users.mobile': 'Mobile',
    'admin.users.tablet': 'Tablette',
    'admin.users.lastLogin': 'Dernière connexion',
    'admin.users.pageViews': 'Pages vues',
    'admin.users.downloads': 'Téléchargements',
    'admin.users.active': 'Actif',
    'admin.users.inactive': 'Inactif',
    'admin.users.banned': 'Banni',
    'admin.users.pending': 'En attente',
    'admin.users.user': 'Utilisateur',
    'admin.users.admin': 'Administrateur',
    'admin.users.moderator': 'Modérateur',
    
    // Admin - Artists Page (additional)
    'admin.artists.title': 'Gestion des Artistes',
    'admin.artists.subtitle': 'Gérer les artistes, leurs profils et les chansons associées',
    'admin.artists.addArtist': 'Ajouter un Artiste',
    'admin.artists.grid': 'Grille',
    'admin.artists.list': 'Liste',
    'admin.artists.totalArtists': 'Total des Artistes',
    'admin.artists.totalSongs': 'Total des Chansons',
    'admin.artists.avgSongsPerArtist': 'Moy. Chansons/Artiste',
    'admin.artists.noArtists': 'Aucun artiste trouvé',
    'admin.artists.addFirstArtist': 'Commencez par ajouter votre premier artiste',
    'admin.artists.addFirst': 'Ajouter le Premier Artiste',
    'admin.artists.editArtist': 'Modifier l\'Artiste',
    'admin.artists.deleteArtist': 'Supprimer l\'Artiste',
    'admin.artists.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cet artiste ?',
    'admin.artists.deleteSuccess': 'Artiste supprimé avec succès',
    'admin.artists.deleteError': 'Échec de la suppression de l\'artiste',
    'admin.artists.addSuccess': 'Artiste ajouté avec succès',
    'admin.artists.addError': 'Échec de l\'ajout de l\'artiste',
    'admin.artists.updateSuccess': 'Artiste mis à jour avec succès',
    'admin.artists.updateError': 'Échec de la mise à jour de l\'artiste',
    'admin.artists.nameLabel': 'Nom de l\'Artiste',
    'admin.artists.namePlaceholder': 'Entrez le nom de l\'artiste',
    'admin.artists.bioLabel': 'Biographie',
    'admin.artists.bioPlaceholder': 'Entrez la biographie de l\'artiste',
    'admin.artists.imageUrlLabel': 'URL de l\'Image',
    'admin.artists.imageUrlPlaceholder': 'Entrez l\'URL de l\'image',
    'admin.artists.websiteLabel': 'Site Web',
    'admin.artists.websitePlaceholder': 'Entrez l\'URL du site web',
    'admin.artists.save': 'Enregistrer',
    'admin.artists.cancel': 'Annuler',
    
    // Admin - Resources Page
    'admin.resources.title': 'Gestion des Ressources',
    'admin.resources.subtitle': 'Gérer les ressources d\'apprentissage, documents et contenu éducatif',
    'admin.resources.import': 'Importer',
    'admin.resources.addResource': 'Ajouter une Ressource',
    'admin.resources.noResources': 'Aucune ressource trouvée',
    'admin.resources.addFirstResource': 'Commencez par ajouter votre première ressource à la collection',
    'admin.resources.addFirst': 'Ajouter la Première Ressource',
    'admin.resources.totalResources': 'Total des Ressources',
    'admin.resources.totalDownloads': 'Total des Téléchargements',
    'admin.resources.documents': 'Documents',
    'admin.resources.videos': 'Vidéos',
    
    // Admin - Analytics Page
    'admin.analytics.title': 'Tableau de Bord d\'Analyses',
    'admin.analytics.subtitle': 'Informations complètes sur les performances de votre plateforme et l\'engagement des utilisateurs',
    'admin.analytics.exportReport': 'Exporter le Rapport',
    'admin.analytics.totalSongs': 'Total des Chansons',
    'admin.analytics.totalUsers': 'Total des Utilisateurs',
    'admin.analytics.pageViews': 'Pages Vues',
    'admin.analytics.downloads': 'Téléchargements',
    'admin.analytics.userGrowth': 'Croissance des Utilisateurs',
    'admin.analytics.userAcquisitionGrowth': 'Métriques d\'acquisition et de croissance des utilisateurs',
    'admin.analytics.newUsersToday': 'Nouveaux Utilisateurs Aujourd\'hui',
    'admin.analytics.newUsersThisWeek': 'Nouveaux Utilisateurs Cette Semaine',
    'admin.analytics.newUsersThisMonth': 'Nouveaux Utilisateurs Ce Mois',
    'admin.analytics.growthRate': 'Taux de Croissance',
    'admin.analytics.userEngagement': 'Engagement des Utilisateurs',
    'admin.analytics.howUsersInteract': 'Comment les utilisateurs interagissent avec votre plateforme',
    'admin.analytics.avgSessionsPerUser': 'Moy. Sessions/Utilisateur',
    'admin.analytics.avgSessionDuration': 'Durée Moyenne de Session',
    'admin.analytics.bounceRate': 'Taux de Rebond',
    'admin.analytics.activeUsers': 'Utilisateurs Actifs',
    'admin.analytics.mostPopularSongs': 'Chansons les Plus Populaires',
    'admin.analytics.topPerformingSongs': 'Chansons les plus performantes par vues',
    'admin.analytics.by': 'par',
    'admin.analytics.views': 'vues',
    'admin.analytics.mostPopularArtists': 'Artistes les Plus Populaires',
    'admin.analytics.artistsWithMostSongs': 'Artistes avec le plus de chansons',
    'admin.analytics.songs': 'chansons',
    'admin.analytics.artist': 'Artiste',
    
    // Admin - Settings Page
    'admin.settings.title': 'Paramètres',
    'admin.settings.subtitle': 'Configurer les paramètres de votre application et préférences',
    'admin.settings.reset': 'Réinitialiser',
    'admin.settings.saveChanges': 'Enregistrer les Modifications',
    'admin.settings.generalSettings': 'Paramètres Généraux',
    'admin.settings.basicConfiguration': 'Configuration de base de l\'application',
    'admin.settings.siteName': 'Nom du Site',
    'admin.settings.adminEmail': 'Email Administrateur',
    'admin.settings.siteDescription': 'Description du Site',
    'admin.settings.siteUrl': 'URL du Site',
    'admin.settings.databaseSettings': 'Paramètres de la Base de Données',
    'admin.settings.connectionHealth': 'Connexion et état de santé de la base de données',
    'admin.settings.databaseStatus': 'État de la Base de Données',
    'admin.settings.healthy': 'Sain',
    'admin.settings.connection': 'Connexion à Supabase',
    'admin.settings.lastBackup': 'Dernière Sauvegarde',
    'admin.settings.testConnection': 'Tester la Connexion à la Base de Données',
    'admin.settings.securitySettings': 'Paramètres de Sécurité',
    'admin.settings.configureSecurity': 'Configurer la sécurité et les contrôles d\'accès',
    'admin.settings.twoFactorAuth': 'Authentification à Deux Facteurs',
    'admin.settings.require2FA': 'Exiger 2FA pour l\'accès administrateur',
    'admin.settings.ipWhitelist': 'Liste Blanche IP',
    'admin.settings.restrictAdminAccess': 'Restreindre l\'accès administrateur à des IP spécifiques',
    'admin.settings.sessionTimeout': 'Délai d\'Expiration de Session (minutes)',
    'admin.settings.notificationSettings': 'Paramètres de Notification',
    'admin.settings.configureNotifications': 'Configurer les notifications système et alertes',
    'admin.settings.emailNotifications': 'Notifications Email',
    'admin.settings.sendEmailAlerts': 'Envoyer des alertes email pour les événements système',
    'admin.settings.systemAlerts': 'Alertes Système',
    'admin.settings.showSystemAlerts': 'Afficher les alertes système dans le panneau d\'administration',
    'admin.settings.maintenanceMode': 'Mode Maintenance',
    'admin.settings.putSiteInMaintenance': 'Mettre le site en mode maintenance',
    'admin.settings.performanceSettings': 'Paramètres de Performance',
    'admin.settings.optimizePerformance': 'Optimiser les performances et la mise en cache de l\'application',
    'admin.settings.cachingEnabled': 'Cache Activé',
    'admin.settings.enableApplicationCaching': 'Activer la mise en cache de l\'application',
    'admin.settings.cdnEnabled': 'CDN Activé',
    'admin.settings.useCDN': 'Utiliser CDN pour les ressources statiques',
    'admin.settings.compressionEnabled': 'Compression Activée',
    'admin.settings.enableGzipCompression': 'Activer la compression gzip',
    'admin.settings.imageOptimization': 'Optimisation des Images',
    'admin.settings.optimizeImagesAutomatically': 'Optimiser les images automatiquement',
    
    // Admin - Common
    'admin.common.adminPanel': 'Panneau d\'Administration',
    'admin.common.administration': 'ADMINISTRATION',
    'admin.common.dashboard': 'Tableau de Bord',
    'admin.common.songs': 'Chansons',
    'admin.common.artists': 'Artistes',
    'admin.common.users': 'Utilisateurs',
    'admin.common.resources': 'Ressources',
    'admin.common.analytics': 'Analyses',
    'admin.common.settings': 'Paramètres',
    'admin.common.quickActions': 'ACTIONS RAPIDES',
    'admin.common.addSong': 'Ajouter une Chanson',
    'admin.common.viewAnalytics': 'Voir les Analyses',
    'admin.common.adminStats': 'STATISTIQUES ADMIN',
    'admin.common.adminSince': 'Administrateur depuis',
    'admin.common.accessLevel': 'Niveau d\'Accès',
    'admin.common.fullAccess': 'Accès Complet',
    'admin.common.signOut': 'Déconnexion',
    'admin.common.me': 'MOI',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // Initialize with a safe default that works on both server and client
  const [language, setLanguage] = useState<'en' | 'fr'>('en'); // Default to English

  useEffect(() => {
    // Only run on client side
    if (typeof window === 'undefined' || typeof document === 'undefined') return;

    try {
      // Check for language in URL query params first (from middleware)
      const urlParams = new URLSearchParams(window.location.search);
      const urlLang = urlParams.get('lang') as 'en' | 'fr' | null;
      
      // Check for language in cookies (set by middleware)
      const cookieLang = document.cookie
        .split('; ')
        .find(row => row.startsWith('language='))
        ?.split('=')[1] as 'en' | 'fr' | undefined;
      
      // Check localStorage safely
      let storedLang: 'en' | 'fr' | null = null;
      try {
        storedLang = localStorage.getItem('language') as 'en' | 'fr' | null;
      } catch (e) {
        // localStorage might not be available
      }
      
      // Priority: URL param > Cookie > localStorage > Default (English)
      const savedLanguage = urlLang || cookieLang || storedLang;
      
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'fr')) {
        setLanguage(savedLanguage);
        // Only save to localStorage if not from URL/cookie to avoid unnecessary writes
        try {
          if (!urlLang && !cookieLang && storedLang !== savedLanguage) {
            localStorage.setItem('language', savedLanguage);
          }
        } catch (e) {
          // Ignore localStorage errors
        }
      } else {
        // Default to English for new users
        setLanguage('en');
        try {
          localStorage.setItem('language', 'en');
        } catch (e) {
          // Ignore localStorage errors
        }
      }
    } catch (error) {
      // If there's any error accessing browser APIs, default to English
      console.warn('Error initializing language:', error);
      setLanguage('en');
    }
  }, []);

  useEffect(() => {
    // Only run on client side
    if (typeof window === 'undefined') return;

    try {
      // Save language preference to localStorage
      localStorage.setItem('language', language);
    } catch (error) {
      console.warn('Error saving language preference:', error);
    }
  }, [language]);

  const t = (key: string): string => {
    // Always return a string, even if there's an error
    try {
      // Ensure language is valid - default to English if invalid
      const currentLang = (language === 'en' || language === 'fr') ? language : 'en';
      
      // Safely access translations object
      if (!translations || typeof translations !== 'object') {
        return key;
      }
      
      const langTranslations = translations[currentLang];
      
      if (!langTranslations || typeof langTranslations !== 'object') {
        return key;
      }
      
      // Direct key access - use Record type for safety
      const translation = (langTranslations as Record<string, string>)[key];
      
      // Return translation if found, otherwise return the key
      return translation || key;
    } catch (error) {
      // If any error occurs, return the key as fallback
      return key;
    }
  };

  // Ensure we always provide a valid context value
  const contextValue = {
    language: (language === 'en' || language === 'fr') ? language : 'en',
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}